version: "3.4"

services:
  mongo:
    image: mongo
    restart: always
 # volumes:
 #   - ./data:/data/db

  api:
    build: /opt/MCW-Cloud-native-applications/Hands-on lab/lab-files/infrastructure/content-api
    image: content-api
    depends_on:
      - mongo
    environment:
      MONGODB_CONNECTION: mongodb://mongo:27017/contentdb

  web:
    build: /opt/MCW-Cloud-native-applications/Hands-on lab/lab-files/infrastructure/content-web
    image: content-web
    depends_on:
      - api
    environment:
      CONTENT_API_URL: http://api:3001
    ports:
      - "3000:3000"
